- name: Trying
  hosts: all
  
  tasks:
  - name: Installing oneAgent
    command: /bin/sh Dynatrace-OneAgent-Linux-1.181.147.sh APP_LOG_CONTENT_ACCESS=1 INFRA_ONLY=0
    become: true
    become_user: sudo
  - name: Starting oneagent
    service:
       name: oneagent
       state: started
