- name: Trying
  hosts: all
  tasks:
  - name: Downloading file
    get_url: 
      url: https://stg99002.live.dynatrace.com/api/v1/deployment/installer/agent/unix/default/latest?Api-Token=i8r36iXXR_KmkhMPiMfZ_&arch=x86&flavor=default
      dest: /home/hkbhandari/
  - name: Installing oneAgent
    command: /bin/sh Dynatrace-OneAgent-Linux-1.181.147.sh APP_LOG_CONTENT_ACCESS=1 INFRA_ONLY=0
    become: true
    ansible_sudo_pass: Ansible12
  - name: Starting oneagent
    service:
       name: oneagent
       state: started
