- name: Trying
  hosts: all
  become: true
  become_user: sudo
  tasks:
  - name: Installing oneAgent
    command: /bin/sh Dynatrace-OneAgent-Linux-1.181.147.sh APP_LOG_CONTENT_ACCESS=1 INFRA_ONLY=0
   
  - name: Starting oneagent
    service:
       name: oneagent
       state: started
